version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "4001:4000"
    environment:
      - DB_URL=mongodb://mongo:27017/auth2
      - JWT_SECRET=mySuperSecretKey123
      - PORT=4000
    depends_on:
      - mongo
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "5173:80"
    depends_on:
      - server
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge